language: python
python: 2.7
install: pip install -r requirements.txt
script: py.test -s -vv
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: lins05
  password:
    secure: MQ3VEWLeBp9Q4h+GK+fYb+6nNUaVHCW0u2Ufy8LTpUR8hLspTyITscR5yYQwgIJlMj8hWpiP6LufEt53GQz9uvaFnDQqV1UpR97RsdYXVy41kLid2T2LBmLhxad9cjeYXAiPp8rzKFvoASAuL10BSjXtiif1+GPv9ijsT6xR9z8=
  on:
    tags: true
    repo: lins05/slackbot
